name: 'linux'
concurrency:
  group: ${{ github.workflow }}-${{ github.event.number }}-${{ github.event.ref }}
  cancel-in-progress: true
on:
  push:
    branches:
      - '*'
  pull_request:
    branches:
      - '*'

jobs:
  job:
    name: 'py3.10'
    runs-on: ubuntu-20.04
    defaults:
      run:
        shell: bash
    env:
      MNE_LOGGING_LEVEL: 'info'
      MNE_STIM_CHANNEL: 'STI101'
      OPENBLAS_NUM_THREADS: '1'
      PYTHON_VERSION: '3.10'
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: ${{ env.PYTHON_VERSION }}
        name: 'Setup python'
      - shell: bash -el {0}
        run: |
          pip install --upgrade --only-binary=":all:" numpy scipy matplotlib
          pip install --upgrade pyyaml patsy pytest pytest-cov codecov flake8 pydocstyle numpydoc https://github.com/mne-tools/mne-python/archive/main.zip
          pip install -ve .
      - shell: bash -el {0}
        run: pytest mnefun
        name: 'Run tests'
      - shell: bash -el {0}
        run: make flake
      - uses: codecov/codecov-action@v1
        if: success()
        name: 'Upload coverage to CodeCov'
